# Config file for automatic testing at travis-ci.org

language: python

python:

  - "2.7"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r test-requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test
